name: Build do frontend com npm e limpeza de cache

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js 22.12
      uses: actions/setup-node@v4
      with:
        node-version: '22.12'

    - name: Limpar dependências e cache antigo
      working-directory: ./frontend
      run: |
        rm -rf node_modules dist node_modules/.vite

    - name: Instalar dependências
      working-directory: ./frontend
      run: npm install

    - name: Rodar build
      working-directory: ./frontend
      run: npm run build